baseURL = "https://deadstack.io"
languageCode = "en-us"
title = "Deadstack"
[taxonomies]
  category = "categories"
[menu]
  [[menu.main]]
    identifier = "/"
    name = "Trang chủ"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "newsletters"
    name = "Newsletters"
    url = "/newsletters/"
    weight = 2
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 2
[params]
  title = "Deadstacks"
  description = "Kênh công nghệ cùng nhau nghiên cứu nền tảng trong Software Development."